FLAG_MESSAGES = {
    "ENCODING_SUSPECT": "File may contain corrupted characters due to encoding issues",
    "DATE_FORMAT_AMBIGUOUS": "Date could be interpreted multiple ways (DD/MM vs MM/DD)",
    "DATE_OUTSIDE_PERIOD": "Activity date falls outside any defined reporting period",
    "NEGATIVE_QUANTITY": "Quantity is negative (could indicate a return or credit)",
    "ZERO_QUANTITY": "Quantity is zero (likely a data entry error)",
    "MISSING_QUANTITY": "Quantity field is empty",
    "NUMBER_FORMAT_AMBIGUOUS": "Number format is ambiguous (3.500 could mean 3500 or 3.5)",
    "MATERIAL_UNCLASSIFIED": "Material code not in classification table. Cannot determine fuel type.",
    "UNIT_UNRECOGNIZED": "Unit of measure not recognized in conversion table",
    "PLANT_NOT_FOUND": "Plant code not found in lookup table",
    "CONVERSION_FACTOR_MISSING": "Cannot convert this unit to MJ (no conversion factor available)",
    "EMISSION_FACTOR_FALLBACK": "Used global emission factor (country-specific not available)",
    "EMISSION_FACTOR_VINTAGE_OLD": "Emission factor is more than 2 years old",
    "IATA_CODE_NOT_FOUND": "Airport code not found in database",
    "CABIN_CLASS_ASSUMED": "Cabin class not provided, assumed Economy",
    "NIGHTS_ZERO": "Check-in and check-out are same date (zero nights)",
    "DISTANCE_UNAVAILABLE": "Distance not provided (cannot calculate emissions)",
    "UNKNOWN_EXPENSE_TYPE": "Expense type not recognized",
    "READ_ESTIMATED": "Utility reading is estimated, not actual meter reading",
    "BILLING_PERIOD_GAP": "Possible missing billing period detected",
    "BILLING_PERIOD_OVERLAP": "Billing period overlaps with another bill for same meter",
    "OUTLIER_HIGH": "Value significantly higher than average for this plant/material",
    "OUTLIER_LOW": "Value significantly lower than average",
    "DUPLICATE_SUSPECTED": "Possible duplicate entry detected",
}
