# Generated by Django 4.2.23 on 2026-05-27 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLookup',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroupLookup',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('FUEL', 'Fuel'), ('NON_FUEL', 'Non-Fuel'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('plant_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UoMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=10)),
                ('material_type', models.CharField(blank=True, max_length=50, null=True)),
                ('to_unit', models.CharField(max_length=10)),
                ('multiplier', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                'unique_together': {('from_unit', 'material_type', 'to_unit')},
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('DEFRA', 'DEFRA'), ('EPA', 'EPA'), ('CEA', 'CEA'), ('CUSTOM', 'Custom')], max_length=20)),
                ('vintage_year', models.IntegerField()),
                ('activity_type', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('numerator_unit', models.CharField(default='kgCO2e', max_length=20)),
                ('denominator_unit', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['activity_type', 'country_code', 'vintage_year'], name='factors_emi_activit_869f4c_idx')],
            },
        ),
    ]
