# Generated by Django 4.2.23 on 2026-05-27 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawActivityRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('OK', 'OK'), ('PARSE_ERROR', 'Parse Error')], default='OK', max_length=20)),
                ('parse_error', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('FUEL', 'Fuel'), ('NON_FUEL', 'Non-Fuel'), ('ELECTRICITY', 'Electricity'), ('TRAVEL_FLIGHT', 'Travel Flight'), ('TRAVEL_HOTEL', 'Travel Hotel'), ('TRAVEL_GROUND', 'Travel Ground'), ('OUT_OF_SCOPE', 'Out of Scope'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'parse_status'], name='parsers_raw_batch_i_6b24b0_idx'), models.Index(fields=['batch', 'classification'], name='parsers_raw_batch_i_1d1da2_idx')],
            },
        ),
    ]
