# Generated by Django 4.2.23 on 2026-05-27 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('parsers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factors', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=20)),
                ('scope', models.IntegerField()),
                ('scope_3_category', models.IntegerField(blank=True, null=True)),
                ('activity_subtype', models.CharField(max_length=50)),
                ('raw_quantity', models.CharField(blank=True, max_length=50)),
                ('raw_unit', models.CharField(blank=True, max_length=20)),
                ('raw_date_text', models.CharField(blank=True, max_length=50)),
                ('raw_location_code', models.CharField(blank=True, max_length=50)),
                ('activity_period_start', models.DateField(blank=True, null=True)),
                ('activity_period_end', models.DateField(blank=True, null=True)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=20)),
                ('resolved_location', models.CharField(blank=True, max_length=255)),
                ('resolved_country_code', models.CharField(blank=True, max_length=2)),
                ('resolved_material_name', models.CharField(blank=True, max_length=255)),
                ('resolved_material_category', models.CharField(blank=True, max_length=100)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('conversion_display', models.CharField(blank=True, max_length=500)),
                ('co2e_display', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('flags', models.JSONField(default=list)),
                ('flag_summary', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_rows', to='ingestion.ingestionbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activities', to='clients.client')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='factors.emissionfactor')),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='parsers.rawactivityrow')),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='clients.reportingperiod')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'status'], name='normalizati_client__63c98b_idx'), models.Index(fields=['client', 'scope'], name='normalizati_client__73ee29_idx'), models.Index(fields=['batch', 'status'], name='normalizati_batch_i_cd85aa_idx'), models.Index(fields=['batch', 'scope'], name='normalizati_batch_i_1dd4e8_idx')],
            },
        ),
    ]
